from django.db import models
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles

LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted([(item, item) for item in get_all_styles()])

class Resumen (models.Model):	
	identificacion = models.CharField(db_index=True,max_length=20, default='0')
	total_oper_pendientes = models.FloatField(default='0')
	total_oper_liquidadas = models.FloatField(default='0')
	total_oper_anuladas = models.FloatField(default='0')
	total_tran_eur = models.FloatField(default='0')
	total_tran_usd = models.FloatField(default='0')
	total_tran_cad = models.FloatField(default='0')
	total_oper_v = models.FloatField(default='0')
	total_oper_c = models.FloatField(default='0')
	total_oper_j = models.FloatField(default='0')
	avg_valor_usd  = models.FloatField(default='0')
	monto_usd_q25  = models.FloatField(default='0')
	monto_usd_q50  = models.FloatField(default='0')
	monto_usd_q75  = models.FloatField(default='0')
	maxim_d_sin_oper = models.FloatField(default='0')	
	avg_dias = models.FloatField(default='0')
	max_dias_sin_transar = models.FloatField(default='0')
	min_dias_sin_transar = models.FloatField(default='0')
	dias_sin_transar_q25 = models.FloatField(default='0')
	dias_sin_transar_q50 = models.FloatField(default='0')
	dias_sin_transar_q75 = models.FloatField(default='0')
	tipo_identificacion  = models.CharField(max_length=50, default='NA',blank=True)
	primer_apellido      = models.CharField(max_length=50, default='NA',blank=True)
	segundo_apellido	 = models.CharField(max_length=50, default='NA',blank=True)
	nombre= models.CharField(max_length=50, default='NA',blank=True)
	fecha_nacimiento     = models.CharField(max_length=50, default='NA',blank=True)
	estado = models.CharField(max_length=50, default='NA',blank=True)
	direccion = models.CharField(max_length=200, default='NA',blank=True)
	ciudad = models.CharField(max_length=50, default='NA',blank=True)
	pais = models.CharField(max_length=50, default='NA',blank=True)
	celular= models.CharField(max_length=50, default='NA',blank=True)
	email = models.CharField(max_length=100, default='NA',blank=True)
	telefono= models.CharField(max_length=50, default='NA',blank=True)
	cod_tipo_id = models.CharField(max_length=50, default='NA',blank=True)

class ResumenFiltros (models.Model):	
	identificacion = models.CharField(db_index=True,max_length=20, default='0')
	nombre= models.CharField(max_length=50, default='NA',blank=True)
	primer_apellido      = models.CharField(max_length=50, default='NA',blank=True)

class ResumenProductosUsuario (models.Model): 
	identificacion   = models.CharField(db_index=True,max_length=20, default='0')
	numero_cuenta    = models.CharField(max_length=20, default='0')
	nombre_producto  = models.CharField(max_length=100, default='NA',null=True)

class  Cliente (models.Model) :
	identificacion   = models.CharField(db_index=True,max_length=20, default='0')
	tipo_identificacion  = models.CharField(max_length=50, default='NA',blank=True)
	descripcion = models.CharField(max_length=100, default='NA',null=True)
	tipo_persona = models.CharField(max_length=20, default='NA',blank=True)

class ResumenInfoPersonaNatural (models.Model) :
    id_contacto = models.CharField(max_length=20, default='0')
    fecha_vinculacion= models.CharField(max_length=50, default='NA',null=True)
    fecha_ultima_actualizacion = models.CharField(max_length=50, default='NA',null=True) 
    tipo_identificacion = models.CharField(max_length=30, default='NA',null=True)
    identificacion = models.CharField(db_index=True,max_length=20, default='NA',null=True)
    nombre = models.CharField(max_length=100, default='NA',null=True)
    primer_apellido = models.CharField(max_length=100, default='NA',null=True)
    segundo_apellido = models.CharField(max_length=100, default='NA',null=True) 
    fecha_expedicion = models.CharField(max_length=100, default='NA',null=True)
    lugar_expedicion = models.CharField(max_length=100, default='NA',null=True)
    fecha_nacimiento = models.CharField(max_length=100, default='NA',null=True)
    lugar_nacimiento = models.CharField(max_length=100, default='NA',null=True)
    celular_principal = models.CharField(max_length=100, default='NA',null=True)
    email_principal = models.CharField(max_length=100, default='NA',null=True)
    direccion_contacto_corta = models.CharField(max_length=250, default='NA',null=True)
    pais = models.CharField(max_length=100, default='NA',null=True)
    lugar_residencia = models.CharField(max_length=100, default='NA',null=True)
    ind_persona_natural_negocio = models.CharField(max_length=100, default='NA',null=True)
    ciiu = models.CharField(max_length=100, default='NA',null=True)
    actividad_laboral = models.CharField(max_length=100, default='NA',null=True)
    operaciones_internacionales = models.CharField(max_length=100, default='NA',null=True)
    peps = models.CharField(max_length=100, default='NA',null=True)
    impactado_fatca = models.CharField(max_length=100, default='NA',null=True)
    tiene_residenc_legal_otro_pais = models.CharField(max_length=100, default='NA',null=True)
    direccion_otro_pais  = models.CharField(max_length=250, default='NA',null=True)
    pais_de_la_direccion = models.CharField(max_length=250, default='NA',null=True)
    nro_tin = models.CharField(max_length=100, default='NA',null=True)
    periodo = models.FloatField(default='0')
    total_ingresos = models.CharField(max_length=100, default='0',null=True)
    total_egresos = models.CharField(max_length=100, default='0',null=True)
    total_activos = models.CharField(max_length=100, default='0',null=True)
    total_pasivos = models.CharField(max_length=100, default='0',null=True)
    antiguedad = models.CharField(max_length=100, default='0',null=True)
    ciiu_restr = models.CharField(max_length=10, default='NA',null=True)
    ciiu_restr_desc = models.CharField(max_length=50, default='NA',null=True)
    segmento_comercial = models.CharField(max_length=50, default='NA',null=True)
    lista_restr = models.CharField(max_length=5, default='NA',null=True)
    cupo = models.FloatField(default='0')
    subsegmento_comercial = models.CharField(max_length=50, default='NA',null=True)
    segmento_color = models.CharField(max_length=50, default='NA',null=True)
    
class ResumenFinancieraMe (models.Model) :	
	id_contacto = models.CharField(max_length=20, default='0')
	identificacion = models.CharField(db_index=True,max_length=20, default='NA',blank=True)
	total_transacciones_eur = models.FloatField(default='0')
	total_transacciones_usd = models.FloatField(default='0')
	total_transacciones_cad = models.FloatField(default='0')
	max_d_sin_oper = models.FloatField(default='0')
	max_dias_sin_transar = models.FloatField(default='0')
	min_dias_sin_transar = models.FloatField(default='0')
	avg_dias = models.FloatField(default='0')
	dias_sin_transar_q25 = models.FloatField(default='0')
	dias_sin_transar_q50 = models.FloatField(default='0')
	dias_sin_transar_q75 = models.FloatField(default='0')
	avg_valor_usd = models.FloatField(default='0')
	monto_usd_q25 = models.FloatField(default='0')
	monto_usd_q50 = models.FloatField(default='0')
	monto_usd_q75 = models.FloatField(default='0')
	antiguedad_transaccional = models.FloatField(default='0')
	
	
class ResumenInfoPersonaJuridica (models.Model) :
    id_empresa = models.CharField(max_length=20, default='0')
    fecha_vinculacion = models.CharField(max_length=10, default='NA',null=True)
    fecha_ultima_actualizacion  = models.CharField(max_length=10, default='NA',null=True)
    tipo_de_identificacion = models.CharField(max_length=30, default='NA',null=True)
    identificacion = models.CharField(max_length=20, default='NA',null=True)
    razon_social = models.CharField(max_length=100, default='NA',null=True)
    pais_constitucion = models.CharField(max_length=100, default='NA',null=True)
    ciudad = models.CharField(max_length=100, default='NA',null=True)
    fecha_de_constitucion = models.CharField(max_length=10, default='NA',null=True)
    ciuu  = models.CharField(max_length=100, default='NA',null=True)
    actividad_economica = models.CharField(max_length=100, default='NA',null=True)
    tipo_de_empresa = models.CharField(max_length=100, default='NA',null=True)
    clase_empresa = models.CharField(max_length=100, default='NA',null=True)
    celular_principal = models.CharField(max_length=100, default='NA',null=True)
    correo_electronico = models.CharField(max_length=100, default='NA',null=True)
    direccion = models.CharField(max_length=200, default='NA',null=True)
    ciudad_direccion = models.CharField(max_length=100, default='NA',null=True)
    segmento_empresarial = models.CharField(max_length=100, default='NA',null=True)
    total_ingresos = models.CharField(max_length=100, default='0',null=True)
    total_egresos = models.CharField(max_length=100, default='0',null=True)
    total_activos = models.CharField(max_length=100, default='0',null=True)
    total_pasivos = models.CharField(max_length=100, default='0',null=True)
    empresa_cotiza_en_bolsa = models.CharField(max_length=100, default='NA',null=True)
    operaciones_internacionales = models.CharField(max_length=100, default='NA',null=True)
    empresa_es_vigilada_por_superi = models.CharField(max_length=100, default='NA',null=True)
    impactado_fatca = models.CharField(max_length=100, default='NA',null=True)
    resid_fiscal_en_pais_dif_a_col = models.CharField(max_length=100, default='NA',null=True)
    numero_tin = models.CharField(max_length=100, default='NA',null=True)
    controla_lavado_de_activos = models.CharField(max_length=100, default='NA',null=True)
    cliente_peps = models.CharField(max_length=100, default='NA',null=True)
    maneja_recursos_publicos = models.CharField(max_length=100, default='NA',null=True)
    antiguedad = models.CharField(max_length=100, default='0',null=True)
    ciiu_restr = models.CharField(max_length=10, default='NA',null=True)
    ciiu_restr_desc = models.CharField(max_length=50, default='NA',null=True)
    segmento_comercial = models.CharField(max_length=50, default='NA',null=True)
    lista_restr = models.CharField(max_length=5, default='NA',null=True)
    cupo = models.FloatField(default='0')
    subsegmento_comercial = models.CharField(max_length=50, default='NA',null=True)
    segmento_color = models.CharField(max_length=50, default='NA',null=True)
