# Generated by Django 2.2.5 on 2019-10-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consdavivienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='celular',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='resumen',
            name='ciudad',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='resumen',
            name='cod_tipo_id',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='resumen',
            name='direccion',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='resumen',
            name='email',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='resumen',
            name='estado',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='resumen',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='resumen',
            name='nombre',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='resumen',
            name='pais',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='resumen',
            name='primer_apellido',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='resumen',
            name='segundo_apellido',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='resumen',
            name='telefono',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='resumen',
            name='tipo_identificacion',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
    ]
