# Generated by Django 2.2.5 on 2019-10-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consdavivienda', '0002_auto_20191009_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='direccion',
            field=models.CharField(blank=True, default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='email',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
