# Generated by Django 2.2.5 on 2020-01-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consdavivienda', '0003_auto_20191009_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(db_index=True, default='0', max_length=20)),
                ('tipo_identificacion', models.CharField(blank=True, default='NA', max_length=50)),
                ('nombre', models.CharField(blank=True, default='NA', max_length=50)),
                ('primer_apellido', models.CharField(blank=True, default='NA', max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, default='NA', max_length=50)),
                ('tipo_persona', models.CharField(blank=True, default='NA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenFiltros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(db_index=True, default='0', max_length=20)),
                ('nombre', models.CharField(blank=True, default='NA', max_length=50)),
                ('primer_apellido', models.CharField(blank=True, default='NA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenFinancieraMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contacto', models.CharField(default='0', max_length=20)),
                ('identificacion', models.CharField(blank=True, db_index=True, default='NA', max_length=20)),
                ('total_transacciones_eur', models.FloatField(default='0')),
                ('total_transacciones_usd', models.FloatField(default='0')),
                ('total_transacciones_cad', models.FloatField(default='0')),
                ('max_d_sin_oper', models.FloatField(default='0')),
                ('max_dias_sin_transar', models.FloatField(default='0')),
                ('min_dias_sin_transar', models.FloatField(default='0')),
                ('avg_dias', models.FloatField(default='0')),
                ('dias_sin_transar_q25', models.FloatField(default='0')),
                ('dias_sin_transar_q50', models.FloatField(default='0')),
                ('dias_sin_transar_q75', models.FloatField(default='0')),
                ('avg_valor_usd', models.FloatField(default='0')),
                ('monto_usd_q25', models.FloatField(default='0')),
                ('monto_usd_q50', models.FloatField(default='0')),
                ('monto_usd_q75', models.FloatField(default='0')),
                ('antiguedad_transaccional', models.FloatField(default='0')),
                ('antiguedad', models.FloatField(default='0')),
                ('total_ingresos', models.FloatField(default='0')),
                ('total_egresos', models.FloatField(default='0')),
                ('total_pasivos', models.FloatField(default='0')),
                ('total_activos', models.FloatField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='ResumenInfoPersonaNatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contacto', models.CharField(default='0', max_length=20)),
                ('fecha_vinculacion', models.CharField(blank=True, default='NA', max_length=50)),
                ('fecha_ultima_actualizacion', models.CharField(blank=True, default='NA', max_length=50)),
                ('tipo_identificacion', models.CharField(blank=True, default='NA', max_length=10)),
                ('identificacion', models.CharField(blank=True, db_index=True, default='NA', max_length=20)),
                ('nombre', models.CharField(blank=True, default='NA', max_length=50)),
                ('primer_apellido', models.CharField(blank=True, default='NA', max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, default='NA', max_length=50)),
                ('fecha_expedicion', models.CharField(blank=True, default='NA', max_length=50)),
                ('lugar_expedicion', models.CharField(blank=True, default='NA', max_length=50)),
                ('fecha_nacimiento', models.CharField(blank=True, default='NA', max_length=50)),
                ('lugar_nacimiento', models.CharField(blank=True, default='NA', max_length=50)),
                ('celular_principal', models.CharField(blank=True, default='NA', max_length=50)),
                ('email_principal', models.CharField(blank=True, default='NA', max_length=50)),
                ('direccion_contacto_corta', models.CharField(blank=True, default='NA', max_length=50)),
                ('pais', models.CharField(blank=True, default='NA', max_length=50)),
                ('lugar_residencia', models.CharField(blank=True, default='NA', max_length=50)),
                ('ind_persona_natural_negocio', models.CharField(blank=True, default='NA', max_length=50)),
                ('ciiu', models.CharField(blank=True, default='NA', max_length=50)),
                ('actividad_laboral', models.CharField(blank=True, default='NA', max_length=50)),
                ('operaciones_internacionales', models.CharField(blank=True, default='NA', max_length=50)),
                ('peps', models.CharField(blank=True, default='NA', max_length=50)),
                ('impactado_fatca', models.CharField(blank=True, default='NA', max_length=50)),
                ('tiene_residenc_legal_otro_pais', models.CharField(blank=True, default='NA', max_length=50)),
                ('direccion_otro_pais', models.CharField(blank=True, default='NA', max_length=50)),
                ('pais_de_la_direccion', models.CharField(blank=True, default='NA', max_length=50)),
                ('nro_tin', models.FloatField(default='0')),
                ('periodo', models.FloatField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='ResumenProductosUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(db_index=True, default='0', max_length=20)),
                ('numero_cuenta', models.CharField(default='0', max_length=20)),
                ('nombre_producto', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
