# Generated by Django 2.2.5 on 2020-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consdavivienda', '0005_auto_20200127_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='primer_apellido',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segundo_apellido',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
    ]
