# Generated by Django 2.2.5 on 2020-01-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consdavivienda', '0006_auto_20200127_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenInfoPersonaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.CharField(default='0', max_length=20)),
                ('fecha_vinculacion', models.CharField(default='NA', max_length=10, null=True)),
                ('fecha_ultima_actualizacion', models.CharField(default='NA', max_length=10, null=True)),
                ('tipo_de_identificacion', models.CharField(default='NA', max_length=10, null=True)),
                ('identificacion', models.CharField(default='NA', max_length=20, null=True)),
                ('razon_social', models.CharField(default='NA', max_length=100, null=True)),
                ('pais_constitucion', models.CharField(default='NA', max_length=100, null=True)),
                ('ciudad', models.CharField(default='NA', max_length=100, null=True)),
                ('fecha_de_constitucion', models.CharField(default='NA', max_length=10, null=True)),
                ('ciuu', models.CharField(default='NA', max_length=100, null=True)),
                ('actividad_economica', models.CharField(default='NA', max_length=100, null=True)),
                ('tipo_de_empresa', models.CharField(default='NA', max_length=100, null=True)),
                ('clase_empresa', models.CharField(default='NA', max_length=100, null=True)),
                ('celular_principal', models.CharField(default='NA', max_length=100, null=True)),
                ('correo_electronico', models.CharField(default='NA', max_length=100, null=True)),
                ('direccion', models.CharField(default='NA', max_length=100, null=True)),
                ('ciudad_direccion', models.CharField(default='NA', max_length=100, null=True)),
                ('segmento_empresarial', models.CharField(default='NA', max_length=100, null=True)),
                ('total_ingresos', models.FloatField(default='0')),
                ('total_egresos', models.FloatField(default='0')),
                ('total_activos', models.FloatField(default='0')),
                ('total_pasivos', models.FloatField(default='0')),
                ('empresa_cotiza_en_bolsa', models.CharField(default='NA', max_length=100, null=True)),
                ('operaciones_internacionales', models.CharField(default='NA', max_length=100, null=True)),
                ('empresa_es_vigilada_por_superi', models.CharField(default='NA', max_length=100, null=True)),
                ('impactado_fatca', models.CharField(default='NA', max_length=100, null=True)),
                ('resid_fiscal_en_pais_dif_a_col', models.CharField(default='NA', max_length=100, null=True)),
                ('numero_tin', models.CharField(default='NA', max_length=100, null=True)),
                ('controla_lavado_de_activos', models.CharField(default='NA', max_length=100, null=True)),
                ('cliente_peps', models.CharField(default='NA', max_length=100, null=True)),
                ('maneja_recursos_publicos', models.CharField(default='NA', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resumenfinancierame',
            name='antiguedad',
        ),
        migrations.RemoveField(
            model_name='resumenfinancierame',
            name='total_activos',
        ),
        migrations.RemoveField(
            model_name='resumenfinancierame',
            name='total_egresos',
        ),
        migrations.RemoveField(
            model_name='resumenfinancierame',
            name='total_ingresos',
        ),
        migrations.RemoveField(
            model_name='resumenfinancierame',
            name='total_pasivos',
        ),
        migrations.AddField(
            model_name='resumeninfopersonanatural',
            name='antiguedad',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='resumeninfopersonanatural',
            name='total_activos',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='resumeninfopersonanatural',
            name='total_egresos',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='resumeninfopersonanatural',
            name='total_ingresos',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='resumeninfopersonanatural',
            name='total_pasivos',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='actividad_laboral',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='celular_principal',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='ciiu',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='direccion_contacto_corta',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='direccion_otro_pais',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='email_principal',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='fecha_expedicion',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='fecha_nacimiento',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='fecha_ultima_actualizacion',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='fecha_vinculacion',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='identificacion',
            field=models.CharField(db_index=True, default='NA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='impactado_fatca',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='ind_persona_natural_negocio',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='lugar_expedicion',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='lugar_nacimiento',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='lugar_residencia',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='nombre',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='operaciones_internacionales',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='pais',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='pais_de_la_direccion',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='peps',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='primer_apellido',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='segundo_apellido',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='tiene_residenc_legal_otro_pais',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='tipo_identificacion',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
    ]
