# Generated by Django 2.2.5 on 2020-01-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consdavivienda', '0007_auto_20200127_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='segundo_apellido',
        ),
        migrations.AddField(
            model_name='cliente',
            name='descripcion',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
