# Generated by Django 2.2.5 on 2020-01-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consdavivienda', '0008_auto_20200128_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeninfopersonajuridica',
            name='tipo_de_identificacion',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='tipo_identificacion',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
    ]
