# Generated by Django 2.2.5 on 2020-01-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consdavivienda', '0009_auto_20200128_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='nro_tin',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
