# Generated by Django 2.2.5 on 2020-01-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consdavivienda', '0010_auto_20200128_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='antiguedad',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='total_activos',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='total_egresos',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='total_ingresos',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='total_pasivos',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
