# Generated by Django 2.2.5 on 2020-01-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consdavivienda', '0011_auto_20200128_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='direccion_contacto_corta',
            field=models.CharField(default='NA', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='direccion_otro_pais',
            field=models.CharField(default='NA', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resumeninfopersonanatural',
            name='pais_de_la_direccion',
            field=models.CharField(default='NA', max_length=250, null=True),
        ),
    ]
